/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#00a2f4",
        "surface-tint": "#9d4300",
        "tertiary-fixed": "#cde5ff",
        "text-muted": "#737373",
        "inverse-surface": "#3c2d26",
        "on-surface": "#251913",
        "on-tertiary-fixed-variant": "#004b74",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-secondary-container": "#636262",
        "sidebar-bg": "#0A0A0A",
        "status-paid": "#22C55E",
        "on-background": "#251913",
        "primary-fixed-dim": "#ffb690",
        "on-primary-container": "#582200",
        "surface-container-low": "#fff1eb",
        "canvas-bg": "#FAFAFA",
        "inverse-on-surface": "#ffede6",
        "status-pending": "#F59E0B",
        "surface-container": "#ffeae0",
        "on-secondary-fixed-variant": "#474746",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#f97316",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#001d32",
        "surface-container-highest": "#f6ded3",
        "text-primary": "#171717",
        "surface-card": "#FFFFFF",
        "on-tertiary-container": "#003554",
        "secondary-container": "#e2dfde",
        "background": "#fff8f6",
        "status-in-progress": "#3B82F6",
        "surface-container-high": "#fce3d9",
        "border-subtle": "#E5E5E5",
        "primary": "#9d4300",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#1c1b1b",
        "tertiary": "#006398",
        "on-primary-fixed": "#341100",
        "surface-bright": "#fff8f6",
        "on-primary-fixed-variant": "#783200",
        "tertiary-fixed-dim": "#93ccff",
        "outline": "#8c7164",
        "secondary": "#5f5e5e",
        "secondary-fixed-dim": "#c8c6c5",
        "outline-variant": "#e0c0b1",
        "surface-variant": "#f6ded3",
        "on-surface-variant": "#584237",
        "primary-fixed": "#ffdbca",
        "secondary-fixed": "#e5e2e1",
        "on-secondary": "#ffffff",
        "surface": "#fff8f6",
        "inverse-primary": "#ffb690",
        "surface-dim": "#edd5cb"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-gap": "0.5rem",
        "section-gap": "2.5rem",
        "card-padding": "1.25rem",
        "container-margin": "2rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        "headline": ["Work Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "metric-value": ["Inter"],
        "body-sm": ["Inter"],
        "body-base": ["Inter"],
        "table-data": ["Inter"],
        "heading-md": ["Inter"],
        "display-lg": ["Inter"],
        "label-caps": ["Inter"]
      },
      fontSize: {
        "metric-value": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-base": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "table-data": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "heading-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "display-lg": ["30px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
